### ISSUE TITLE
延迟任务

### ISSUE THREAD

**Issue by taowanlai** [limbo-world/flowjob#30]
今天在文章看到这个项目，但是看描述好像没有延迟消息的相关介绍，就是类似订单30m后自动取消的这种模式，目前是有这块支持么？

**Comment by oDevilo** [comment]
感谢支持，这个后面有考虑的，下个版本中会增加，敬请期待

**Comment by oDevilo** [comment]
https://github.com/limbo-world/flowjob/pull/31
最新版本 2.1.0 开放此能力
